catalogMode: strict

catalogs:
  dev:
    "@fast-check/vitest": ^0.2.0
    "@vitest/coverage-v8": ^4.0.17
    knip: ^5.81.0
    publint: ^0.3.5
    tsdown: ^0.19.0
    unplugin-unused: ^0.5.0
    vitest: ^4.0.15
  jsr:
    "@std/yaml": jsr:@std/yaml@^1
  release:
    bumpp: ^10.2.3
    changelogithub: ^13.16.1

onlyBuiltDependencies:
  - esbuild

shellEmulator: true

enablePrePostScripts: true
trustPolicy: no-downgrade
minimumReleaseAge: 1440
